[theme]
base = "light"
primaryColor = "#497b6a"
backgroundColor = "#f5f7f3"
secondaryBackgroundColor = "#edf2e8"
textColor = "#304d43"
font = "sans serif"

[server]
enableStaticServing = true
headless = true

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
